env:
  node: true
  jest: true
  es2021: true
extends:
  - airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions: 0
  import/prefer-default-export: 0
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  class-methods-use-this: 0
  no-use-before-define: ["error", { "functions": false }]
  object-curly-newline: 0
  no-param-reassign: ["error", { "props": false }]
  